#!/bin/bash
#
# dnsmasq 설치 및 구성 스크립트
# Oracle RAC SCAN 및 호스트 이름 해석을 위한 DNS 서버 설정
#
# 실행 위치: node2
# 요구사항: 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9
#

set -e  # 에러 발생 시 즉시 중단
set -u  # 정의되지 않은 변수 사용 시 에러

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 로그 함수
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Root 권한 확인
if [[ $EUID -ne 0 ]]; then
   log_error "이 스크립트는 root 권한으로 실행되어야 합니다."
   exit 1
fi

log_info "dnsmasq 설치 및 구성 시작..."

# 1. dnsmasq 설치
log_info "dnsmasq 패키지 설치 중..."
if rpm -q dnsmasq &>/dev/null; then
    log_warn "dnsmasq가 이미 설치되어 있습니다."
else
    dnf install -y dnsmasq
    log_info "dnsmasq 설치 완료"
fi

# 2. dnsmasq 구성 파일 백업
DNSMASQ_CONF="/etc/dnsmasq.conf"
if [[ -f "${DNSMASQ_CONF}" ]]; then
    if [[ ! -f "${DNSMASQ_CONF}.orig" ]]; then
        log_info "기존 dnsmasq 구성 파일 백업 중..."
        cp "${DNSMASQ_CONF}" "${DNSMASQ_CONF}.orig"
    fi
fi

# 3. dnsmasq 구성 파일 생성
log_info "dnsmasq 구성 파일 생성 중..."
cat > "${DNSMASQ_CONF}" << 'EOF'
# dnsmasq configuration for Oracle RAC
# Generated by setup_dnsmasq.sh

# Listen on all interfaces
listen-address=::1,127.0.0.1,192.168.1.102

# Do not read /etc/resolv.conf
no-resolv

# Do not read /etc/hosts
no-hosts

# Upstream DNS servers (Google DNS)
server=8.8.8.8
server=8.8.4.4

# Log queries for debugging
log-queries

# Log facility
log-facility=/var/log/dnsmasq.log

# Cache size
cache-size=1000

# Public Network - Node hostnames
address=/node1.localdomain/192.168.1.101
address=/node2.localdomain/192.168.1.102

# Private Network - Node hostnames
address=/node1-priv.localdomain/10.0.0.101
address=/node2-priv.localdomain/10.0.0.102

# VIP addresses
address=/node1-vip.localdomain/192.168.1.111
address=/node2-vip.localdomain/192.168.1.112

# SCAN addresses (Round-robin DNS)
# Oracle RAC requires 3 IP addresses for SCAN
address=/rac-scan.localdomain/192.168.1.121
address=/rac-scan.localdomain/192.168.1.122
address=/rac-scan.localdomain/192.168.1.123

# Domain configuration
domain=localdomain
expand-hosts
EOF

log_info "dnsmasq 구성 파일 생성 완료"

# 4. dnsmasq 구성 파일 검증
log_info "dnsmasq 구성 파일 검증 중..."
if dnsmasq --test; then
    log_info "dnsmasq 구성 파일 검증 성공"
else
    log_error "dnsmasq 구성 파일 검증 실패"
    exit 1
fi

# 5. 방화벽 설정 (firewalld가 실행 중인 경우)
if systemctl is-active --quiet firewalld; then
    log_info "방화벽에 DNS 서비스 추가 중..."
    firewall-cmd --permanent --add-service=dns
    firewall-cmd --reload
    log_info "방화벽 설정 완료"
else
    log_warn "firewalld가 실행 중이지 않습니다. 방화벽 설정을 건너뜁니다."
fi

# 6. dnsmasq 서비스 활성화 및 시작
log_info "dnsmasq 서비스 활성화 및 시작 중..."
systemctl enable dnsmasq
systemctl restart dnsmasq

# 7. dnsmasq 서비스 상태 확인
if systemctl is-active --quiet dnsmasq; then
    log_info "dnsmasq 서비스가 정상적으로 실행 중입니다."
else
    log_error "dnsmasq 서비스 시작 실패"
    systemctl status dnsmasq
    exit 1
fi

# 8. DNS 해석 테스트
log_info "DNS 해석 테스트 중..."

test_dns() {
    local hostname=$1
    local expected_ip=$2
    
    log_info "테스트: ${hostname} -> ${expected_ip}"
    
    # nslookup 사용 (dig가 없을 수 있음)
    result=$(nslookup "${hostname}" 127.0.0.1 2>/dev/null | grep -A1 "Name:" | grep "Address:" | awk '{print $2}' | head -1)
    
    if [[ -z "${result}" ]]; then
        log_warn "${hostname} 해석 실패 (결과 없음)"
        return 1
    fi
    
    if [[ "${result}" == "${expected_ip}" ]]; then
        log_info "✓ ${hostname} -> ${result}"
        return 0
    else
        log_warn "✗ ${hostname} -> ${result} (예상: ${expected_ip})"
        return 1
    fi
}

# Public Network 호스트 테스트
test_dns "node1.localdomain" "192.168.1.101"
test_dns "node2.localdomain" "192.168.1.102"

# Private Network 호스트 테스트
test_dns "node1-priv.localdomain" "10.0.0.101"
test_dns "node2-priv.localdomain" "10.0.0.102"

# VIP 테스트
test_dns "node1-vip.localdomain" "192.168.1.111"
test_dns "node2-vip.localdomain" "192.168.1.112"

# SCAN 테스트 (라운드 로빈 확인)
log_info "SCAN 라운드 로빈 DNS 테스트 중..."
scan_ips=()
for i in {1..5}; do
    result=$(nslookup "rac-scan.localdomain" 127.0.0.1 2>/dev/null | grep -A1 "Name:" | grep "Address:" | awk '{print $2}' | head -1)
    if [[ -n "${result}" ]]; then
        scan_ips+=("${result}")
    fi
done

# SCAN IP 중복 제거 및 확인
unique_scan_ips=($(printf '%s\n' "${scan_ips[@]}" | sort -u))
log_info "SCAN 해석 결과: ${unique_scan_ips[*]}"

expected_scan_ips=("192.168.1.121" "192.168.1.122" "192.168.1.123")
if [[ ${#unique_scan_ips[@]} -eq 3 ]]; then
    log_info "✓ SCAN 라운드 로빈 DNS 구성 성공 (3개 IP 확인)"
else
    log_warn "✗ SCAN 라운드 로빈 DNS 구성 확인 필요 (${#unique_scan_ips[@]}개 IP 발견)"
fi

# 9. /etc/resolv.conf 업데이트 (선택사항)
log_info "/etc/resolv.conf 확인 중..."
if ! grep -q "nameserver 127.0.0.1" /etc/resolv.conf; then
    log_warn "/etc/resolv.conf에 로컬 DNS 서버가 설정되어 있지 않습니다."
    log_info "수동으로 /etc/resolv.conf를 업데이트하거나 NetworkManager를 구성하세요."
fi

log_info "=========================================="
log_info "dnsmasq 설치 및 구성 완료!"
log_info "=========================================="
log_info "DNS 서버: 192.168.1.102"
log_info "구성 파일: ${DNSMASQ_CONF}"
log_info "로그 파일: /var/log/dnsmasq.log"
log_info ""
log_info "다른 노드에서 이 DNS 서버를 사용하려면:"
log_info "  echo 'nameserver 192.168.1.102' > /etc/resolv.conf"
log_info ""
log_info "또는 NetworkManager를 사용하는 경우:"
log_info "  nmcli con mod <connection-name> ipv4.dns '192.168.1.102'"
log_info "  nmcli con up <connection-name>"
log_info "=========================================="

exit 0
