#!/bin/bash
#
# /etc/hosts 파일 구성 스크립트
# Oracle RAC 노드의 호스트 이름 및 IP 매핑 설정
#
# 실행 위치: 모든 노드 (node1, node2)
# 요구사항: 3.6, 3.7, 3.8, 3.9
#

set -e  # 에러 발생 시 즉시 중단
set -u  # 정의되지 않은 변수 사용 시 에러

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 로그 함수
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Root 권한 확인
if [[ $EUID -ne 0 ]]; then
   log_error "이 스크립트는 root 권한으로 실행되어야 합니다."
   exit 1
fi

log_info "/etc/hosts 파일 구성 시작..."

# 1. /etc/hosts 파일 백업
HOSTS_FILE="/etc/hosts"
if [[ -f "${HOSTS_FILE}" ]]; then
    if [[ ! -f "${HOSTS_FILE}.orig" ]]; then
        log_info "기존 /etc/hosts 파일 백업 중..."
        cp "${HOSTS_FILE}" "${HOSTS_FILE}.orig"
    fi
fi

# 2. Oracle RAC 호스트 엔트리 추가
log_info "Oracle RAC 호스트 엔트리 추가 중..."

# Oracle RAC 섹션 마커
RAC_MARKER_START="# Oracle RAC Hosts - Start"
RAC_MARKER_END="# Oracle RAC Hosts - End"

# 기존 Oracle RAC 섹션 제거 (멱등성 보장)
if grep -q "${RAC_MARKER_START}" "${HOSTS_FILE}"; then
    log_info "기존 Oracle RAC 호스트 엔트리 제거 중..."
    sed -i "/${RAC_MARKER_START}/,/${RAC_MARKER_END}/d" "${HOSTS_FILE}"
fi

# Oracle RAC 호스트 엔트리 생성
cat >> "${HOSTS_FILE}" << 'EOF'

# Oracle RAC Hosts - Start
# Generated by setup_hosts.sh
# Do not edit this section manually

# Public Network - Node hostnames
192.168.1.101   node1.localdomain       node1
192.168.1.102   node2.localdomain       node2

# Private Network - Node hostnames (Interconnect)
10.0.0.101      node1-priv.localdomain  node1-priv
10.0.0.102      node2-priv.localdomain  node2-priv

# Virtual IP (VIP) addresses
192.168.1.111   node1-vip.localdomain   node1-vip
192.168.1.112   node2-vip.localdomain   node2-vip

# SCAN addresses (Single Client Access Name)
# Note: SCAN should be resolved by DNS for proper round-robin
# These entries are for fallback only
192.168.1.121   rac-scan.localdomain    rac-scan
192.168.1.122   rac-scan.localdomain    rac-scan
192.168.1.123   rac-scan.localdomain    rac-scan

# Oracle RAC Hosts - End
EOF

log_info "/etc/hosts 파일 업데이트 완료"

# 3. /etc/hosts 파일 검증
log_info "/etc/hosts 파일 검증 중..."

verify_host() {
    local hostname=$1
    local expected_ip=$2
    
    log_info "검증: ${hostname} -> ${expected_ip}"
    
    # getent를 사용하여 호스트 이름 해석
    result=$(getent hosts "${hostname}" | awk '{print $1}' | head -1 || true)
    
    if [[ -z "${result}" ]]; then
        log_warn "${hostname} 해석 실패 (결과 없음)"
        return 0
    fi
    
    if [[ "${result}" == "${expected_ip}" ]]; then
        log_info "✓ ${hostname} -> ${result}"
        return 0
    else
        log_warn "✗ ${hostname} -> ${result} (예상: ${expected_ip})"
        return 0
    fi
}

# Public Network 호스트 검증
verify_host "node1.localdomain" "192.168.1.101" || true
verify_host "node2.localdomain" "192.168.1.102" || true

# Private Network 호스트 검증
verify_host "node1-priv.localdomain" "10.0.0.101" || true
verify_host "node2-priv.localdomain" "10.0.0.102" || true

# VIP 검증
verify_host "node1-vip.localdomain" "192.168.1.111" || true
verify_host "node2-vip.localdomain" "192.168.1.112" || true

# SCAN 검증 (첫 번째 엔트리만)
verify_host "rac-scan.localdomain" "192.168.1.121" || true

log_info "=========================================="
log_info "/etc/hosts 파일 구성 완료!"
log_info "=========================================="
log_info "구성 파일: ${HOSTS_FILE}"
log_info "백업 파일: ${HOSTS_FILE}.orig"
log_info ""
log_info "참고:"
log_info "  - SCAN 이름은 DNS를 통해 해석되는 것이 권장됩니다."
log_info "  - /etc/hosts의 SCAN 엔트리는 DNS 장애 시 폴백용입니다."
log_info "  - DNS 서버(dnsmasq)를 사용하면 SCAN 라운드 로빈이 제대로 작동합니다."
log_info "=========================================="

exit 0
